version: '3.8'

services:
  pybaseball-mcp:
    build: .
    container_name: pybaseball-mcp-server
    ports:
      - "3000:3000"
    environment:
      - MCP_SERVER_NAME=pybaseball-mcp-server
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount local directory for development
      - .:/app
      # Cache directory for pybaseball data
      - pybaseball-cache:/home/mcp/.pybaseball
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import server; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    container_name: pybaseball-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    profiles:
      - redis

volumes:
  pybaseball-cache:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    name: pybaseball-mcp-network
